### ISSUE TITLE
When decoding a json object that have åäö we get an error

### ISSUE THREAD

**Issue by Taure** [JanHenryNystrom/jhn_stdlib#38]
`json:decode(<<"{\"payload\":\"detta år ett meddelande\"}">>, [maps]).`

If I replace å with a it works.

**Comment by JanHenryNystrom** [comment]
I will check this out but at first look I would guess you have input iso-8859-1 because that will not work.

/Cheers Henry

**Comment by JanHenryNystrom** [comment]
I have now verified json:decode(<<"{\"payload\":\"detta år ett meddelande\"}"/utf8>>, [maps]). works as it should.
