### ISSUE TITLE
ssl:ssl_accept depricated in OTP 24

### ISSUE THREAD

**Issue by Taure** [JanHenryNystrom/jhn_stdlib#40]
===> Compiling jhn_stdlib
src/syslog.erl:360: Warning: ssl:ssl_accept/1 is deprecated and will be removed in OTP 24; use use ssl_handshake/1,2,3 instead
src/syslog.erl:376: Warning: ssl:ssl_accept/1 is deprecated and will be removed in OTP 24; use use ssl_handshake/1,2,3 instead

Looks like syslog will fail in otp 24, tried to look at it but was not sure what the different was.

**Comment by JanHenryNystrom** [comment]
Yep, I have been meaning to get to that one. I will try and look into it this weekend.

**Comment by JanHenryNystrom** [comment]
Fixed in 3.6.2
